package files;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91959
 */
public class home extends javax.swing.JFrame {
    Statement st=null;
    Connection con=null;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        expanel.setVisible(false);
        this.setLocationRelativeTo(null);
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fpanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        expanel = new javax.swing.JPanel();
        cp = new javax.swing.JComboBox<>();
        fert2 = new javax.swing.JComboBox<>();
        war = new javax.swing.JComboBox<>();
        SLS = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        crop = new javax.swing.JButton();
        fertilizer = new javax.swing.JButton();
        warehouse = new javax.swing.JButton();
        seed = new javax.swing.JButton();
        sales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        fpanel.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/General_-_Office_30-512.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fpanelLayout = new javax.swing.GroupLayout(fpanel);
        fpanel.setLayout(fpanelLayout);
        fpanelLayout.setHorizontalGroup(
            fpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fpanelLayout.setVerticalGroup(
            fpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 502, Short.MAX_VALUE))
        );

        jPanel1.add(fpanel);
        fpanel.setBounds(0, 0, 50, 550);

        expanel.setBackground(new java.awt.Color(102, 102, 102));

        cp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CROPS", "Crops produced", "Crops sales", "View" }));
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        fert2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fertilizer", "Fertilizer used", "View", " " }));
        fert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fert2ActionPerformed(evt);
            }
        });

        war.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WAREHOUSE", "ITEM STORED", "WAREHOUSES", " " }));
        war.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warActionPerformed(evt);
            }
        });

        SLS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALES", "Market details", "Sales list", "TotalSales" }));
        SLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLSActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LCln1.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expanelLayout = new javax.swing.GroupLayout(expanel);
        expanel.setLayout(expanelLayout);
        expanelLayout.setHorizontalGroup(
            expanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(expanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fert2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(war, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SLS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        expanelLayout.setVerticalGroup(
            expanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expanelLayout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(fert2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(war, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(SLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel1.add(expanel);
        expanel.setBounds(0, 0, 167, 550);

        crop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/crop.png"))); // NOI18N
        crop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropActionPerformed(evt);
            }
        });
        jPanel1.add(crop);
        crop.setBounds(250, 130, 100, 60);

        fertilizer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/sssss.png"))); // NOI18N
        fertilizer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fertilizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fertilizerActionPerformed(evt);
            }
        });
        jPanel1.add(fertilizer);
        fertilizer.setBounds(520, 270, 90, 90);

        warehouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/warehouseicon.png"))); // NOI18N
        warehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        warehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseActionPerformed(evt);
            }
        });
        jPanel1.add(warehouse);
        warehouse.setBounds(250, 270, 100, 90);

        seed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/seedlogo.png"))); // NOI18N
        seed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedActionPerformed(evt);
            }
        });
        jPanel1.add(seed);
        seed.setBounds(510, 130, 100, 70);

        sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/images (7).png"))); // NOI18N
        sales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        jPanel1.add(sales);
        sales.setBounds(400, 400, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/homepage.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 100, 780, 460);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel3.setText("FARM MANAGEMENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 10, 590, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        TRADE obj=new TRADE();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salesActionPerformed

    private void seedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedActionPerformed
        SEED osb=new SEED();
        osb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seedActionPerformed

    private void cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropActionPerformed
        CROP OBC=new CROP();
        OBC.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_cropActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fpanel.setVisible(true);
        expanel.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        fpanel.setVisible(false);
        expanel.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void fertilizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fertilizerActionPerformed
        FERTILIZER ofj=new FERTILIZER();
        ofj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fertilizerActionPerformed

    private void warehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseActionPerformed
        WAREHOUSE owj=new WAREHOUSE();
        owj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_warehouseActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
      String  cpro=(String)cp.getSelectedItem();
      String cops="view";
      String cs="Crops sales";
      String cs2="Crop produced";
      
             
              
      if(cpro.equalsIgnoreCase(cops))
      {
          cropview ob=new cropview();
          ob.setVisible(true);
                 
      }
      else if(cpro.equalsIgnoreCase(cs))
      {
         cropsales obs=new cropsales();
          obs.setVisible(true);
          
      }
      else if(cpro.equalsIgnoreCase(cs2))
      {
        cropproduced cpr=new cropproduced();
        cpr.setVisible(true);
      }
    }//GEN-LAST:event_cpActionPerformed

    private void warActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warActionPerformed
      String  wdata=(String)war.getSelectedItem();
      String wd="warehouses";
      String ws="ITEM STORED";
      if(wdata.equalsIgnoreCase(wd))
      {
          warehouses wob=new warehouses();
          wob.setVisible(true);
          
      }else if(wdata.equalsIgnoreCase(ws))
      {
          ITEM ob=new ITEM();
          ob.setVisible(true);
      }
    }//GEN-LAST:event_warActionPerformed

    private void SLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLSActionPerformed
       String  sa=(String)SLS.getSelectedItem();
       String m1="Market details";
       String m2="sales list";
       String m3="totalsales";
       if(sa.equalsIgnoreCase(m1))
       {
           market ob=new market();
           ob.setVisible(true);
       }
       else if(sa.equalsIgnoreCase(m2))
       {
           saledata obs=new saledata();
           obs.setVisible(true);
       }
       else if(sa.equalsIgnoreCase(m3))
       {
           totsales obt=new totsales();
           obt.setVisible(true);
       }
    }//GEN-LAST:event_SLSActionPerformed

    private void fert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fert2ActionPerformed
        String f1="view";
        String f2="Fertilizer used";
        String ch=(String)fert2.getSelectedItem();
        if(ch.equalsIgnoreCase(f1))
        {
            fert fob=new fert();
            fob.setVisible(true);
        }
        else if(ch.equalsIgnoreCase(f2))
        {
            fused fob2=new fused();
            fob2.setVisible(true);
        }
    }//GEN-LAST:event_fert2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SLS;
    private javax.swing.JComboBox<String> cp;
    private javax.swing.JButton crop;
    private javax.swing.JPanel expanel;
    private javax.swing.JComboBox<String> fert2;
    private javax.swing.JButton fertilizer;
    private javax.swing.JPanel fpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sales;
    private javax.swing.JButton seed;
    private javax.swing.JComboBox<String> war;
    private javax.swing.JButton warehouse;
    // End of variables declaration//GEN-END:variables
public void connect()
    {
        try
        {
            
        
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Farm_Management","root","root");
        st=con.createStatement();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }   
        }


}
